site_name: FamilyCASA
copyright: 'Copyright &copy; 2023 - 2024 FamilyCASA'
theme:
  logo: https://github.com/FamilyCASA/FamilyCASA.github.io/blob/main/assets/logo.png?raw=true
  name: material
  language: zh
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.top
    - search.share
    - search.highlight
    - search.suggest
    - navigation.footer
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FamilyCASA
    - icon: fontawesome/brands/qq 
      link: https://user.qzone.qq.com/342366274
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html
  - attr_list
  - toc:
      permalink: true
  - tables
plugins:
  - blog
  - search
nav:
  - 全案整配操作培训指南:
    - 西调调·潮家整配: index.md
    - 全案服务十大核心价值: 西调调家居全案服务的十大核心价值.md
    - 为何需要西调调全案设计服务: 为什么需要西调调全案设计服务.md
  
  